name: workflow.yml
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: step1
        uses: actions/checkout@v4

      - name: step2
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: step3
        run: chmod +x ./gradlew

      - name: step4
        run: ./gradlew bootJar -x test

      - name: step5
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: step5
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/git-prac:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/git-prac:latest

      - name: step6
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker stop test || true
            docker rm test || true
            docker rmi ${{ secrets.DOCKER_USERNAME }}/git-prac:latest || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/git-prac:latest
            docker run -d -p 80:8080 \
            -e URL=jdbc:mysql://${{ secrets.RDS_URL }}/todo_db \
            -e USERNAME=${{ secrets.RDS_USERNAME }} \
            -e PASSWORD=${{ secrets.RDS_PASSWORD }} \
            --name git_prac \
            ${{ secrets.DOCKER_USERNAME}}/test:latest
